### ISSUE TITLE
Failed to verify the signature.

### ISSUE THREAD

**Issue by QiangHeisenberg** [njaremko/samael#10]
When verifying the signature of the SAMLResponse returned by the server, I find that the signature verification fails. I do not know the cause. Here's my verification code:
```
let sso_cert_der: &[u8] = &fs::read("/home/hello/src/jks_cer/rust-registry_idp.cer").unwrap();
let response_xml: &[u8] = &fs::read("/home/hello/response.xml").unwrap();
samael::crypto::verify_signed_xml(response_xml, sso_cert_der, Some("ID")).expect("failed to verify response signature");
```

The error message is as follows:

`func=xmlSecOpenSSLAppCertLoadBIO:file=app.c:line=1051:obj=unknown:subj=d2i_X509_bio:error=4:crypto library function failed:openssl error: 218529960: asn1 encoding routines: asn1_check_tlen wrong tag
func=xmlSecOpenSSLAppKeyFromCertLoadBIO:file=app.c:line=781:obj=unknown:subj=xmlSecOpenSSLAppCertLoadBIO:error=1:xmlsec library function failed:
func=xmlSecOpenSSLAppKeyLoadBIO:file=app.c:line=312:obj=unknown:subj=xmlSecOpenSSLAppKeyFromCertLoadBIO:error=1:xmlsec library function failed:
func=xmlSecOpenSSLAppKeyLoadMemory:file=app.c:line=207:obj=unknown:subj=xmlSecOpenSSLAppKeyLoadBIO:error=1:xmlsec library function failed:
thread 'main' panicked at '**failed to verify response signature: XmlSecError { error: KeyLoadError }**', src/main.rs:24:89
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

Also, I never understood what the third parameter was correctly understood.

**Comment by QiangHeisenberg** [comment]
Can someone guide me? Thank you.

**Comment by QiangHeisenberg** [comment]
@njaremko @RavuAlHemio @agrinman @Guiguiprim

**Comment by njaremko** [comment]
It's generally bad form to tag a bunch of people on an issue you just created.

If you googled (or China's equivalent) the error, you'd see it's an issue with your key. 

It might be in PEM format instead of DER, or the data could be garbage, not sure, but it's definitely an issue with parsing your key.

**Comment by QiangHeisenberg** [comment]
I'm sorry for the inappropriate way it was done. That was not my intention.
1) When I use a certificate to authenticate Response, the certificate format is (.CER). It is not a private key in (.pem) format. Is this function not used for certificate verification?
2) What is the purpose of the third parameter (like'some("ID")')?

**Comment by QiangHeisenberg** [comment]
I also found a problem, I don't know if it was a problem with the way I tested it. I entered the following command to test:

`cargo test --features=xmlsec`

The following error occurred:

`error[E0599]: no method named `remove_attribute_ns` found for mutable reference `&mut Node` in the current scope
   --> src/crypto.rs:190:10
    |
190 |     node.remove_attribute_ns(ATTRIB_SIGVER, XMLNS_SIGVER)
    |          ^^^^^^^^^^^^^^^^^^^ help: there is an associated function with a similar name: `remove_attribute``

**Comment by njaremko** [comment]
`.cer` is just a file extension, the content of the file is either in PEM (ascii) or DER (binary) format. The function you used expects it's argument to be in DER format, but it seems like you're passing in either a mangled file, or a PEM encoded key.

**Comment by QiangHeisenberg** [comment]
This is my problem. When importing a public key, the newline character in the public key is ignored. The format fails to be parsed. Thank you for your answer.
