### ISSUE TITLE
Errors when parsing real life metadata

### ISSUE THREAD

**Issue by frcl** [njaremko/samael#11]
Hi, I'm happy to see that someone is building a rust library for saml :)

While experimenting I noticed that with the IdPs I work with metadata is not parsed correctly.

One real life example is the auth infrastructrue of the german research network (example metadata at http://www.aai.dfn.de/fileadmin/metadata/dfn-aai-test-metadata.xml).
When parsing with
```rust
fn get_idp_metadata() -> Result<EntityDescriptor, Box<dyn std::error::Error>> {
    let meta_bytes = fs::read("./dfn-metadata.xml")?;
    let meta = String::from_utf8_lossy(&meta_bytes);
    let idp_metadata: EntityDescriptor = samael::metadata::de::from_str(&meta)?;
    return Ok(idp_metadata);
}
```
the result is an 
```Err("duplicate field `X509Certificate`")```
(Because the signature of the matadata itself contains multiple `X509Certificate`s in its `KeyInfo`, not sure why, but I guess this is allowd)

Another example is Keycloak. I maintain a Keycloak IdP myself and the default saml metadata looks something like [this](https://pastebin.com/zKx9qDFF).
But trying to parse it results in an empty `EntityDescriptor`
```
EntityDescriptor { entity_id: None, id: None, signature: None, valid_until: None, cache_duration: None, role_descriptors: None, idp_sso_descriptors: None, sp_sso_descriptors: None, authn_authority_descriptors: None, attribute_authority_descriptors: None, pdp_descriptors: None, affiliation_descriptors: None, contact_person: None, organization: None }
```

**Comment by njaremko** [comment]
Just want to let you know that I've seen this issue, but I haven't had time to dive into it yet. Thanks for opening the ticket, I suspect a German research network is going to have great metadata for finding edge cases 😛.
