### ISSUE TITLE
Support for IdP creation

### ISSUE THREAD

**Issue by Armiixteryx** [njaremko/samael#14]
Hello,

Does this crate support building an IdP? It seems that there are bits only to build an app as SP.

**Comment by njaremko** [comment]
Currently, no, though someday it likely will

**Comment by josejachuf** [comment]
Hi @njaremko 
This post is old. There are currently support to create an IDP?

Thanks!

**Comment by njaremko** [comment]
Yes, you can make an IDP now

**Comment by josejachuf** [comment]
Could you please give an example?

**Comment by njaremko** [comment]
Writing an IdP is non-trivial. See https://github.com/oxidecomputer/omicron/blob/5f52a74592948b4a6417edfb3457065fe4dd162f/nexus/db-queries/src/authn/silos.rs#L27
