### ISSUE TITLE
Multi-certificate handling

### ISSUE THREAD

**Issue by pythoneer** [njaremko/samael#40]
I am currently facing the problem that a previous test implementation which worked flawlessly started to fail. I am not 100% sure what's going on because i don't have exact insights in what the saml responses from the IdP looked like earlier. 

I have a suspicion though. I use google as IdP to write a service provider + saml login etc. Google gives you a metadata.xml that contains multiple (2) certificates with `<md:KeyDescriptor use="signing">` with different time frames of validity. Is it possible that the samael library depends on which cert is read in first? Or basically what private key google is using for the signature? My suspicion is that previously google was signing the saml response with the private key from the "first" certificate but switched the the "last" one recently. And now samael is looking at the first certificate in the metadata.xml, check fails and does not try the second one in addition in the metadata.xml? I based my assumption roughly on debugging and looking at this code https://github.com/njaremko/samael/blob/4b4811d97ae324da1376624e77e82af18ee108f3/src/crypto.rs#L419-L428

It looks like its loading the first cert in the loop but immediately `break` if that node cannot be verified. I am not too familiar with the saml spec but i would assume that if the IdP puts in multiple certificates in the metadata.xml it is doing so to gradually transition from one cert to another. So while having 2 active certs they can switch the private keys used for signing the saml response. So i would assume that an implementation to check the signature would need to check the xml nodes against all the available certificates and only fail if ALL are invalid and not fail if ONE of them all is invalid before a suitable was found.

EDIT: sorry – i already found a mistake in my logic. It only `break`s when there is a valid one found :/ ... i just looked to long at debug outputs and confused that. But still ... what i found still holds. If i remove the the "first" certificate in the metadata.xml manually the saml response is fine. If i switch the first with the second (so the seconds is possibly read in first) it also works. Just when i have the "old" (but still not expired, but potentially not used by google for its current signature) certificate first it fails. 
     
EDIT2: i did another debugging session and i think my confusion about the !verified was due to the fact that there seems to be a problem when testing the second certificate. If the certificates are in the "wrong" oder (meaning the one not used for the signature comes first) i get this line

```
func=xmlSecOpenSSLEvpSignatureVerify:file=evp_signatures.c:line=453:obj=rsa-sha256:subj=unknown:error=18:data do not match:details=EVP_VerifyFinal: signature verification failed
```
when doing the second loop run with the "now correct" certificate this shows up in my terminal

```
func=xmlSecDSigCtxProcessSignatureNode:file=xmldsig.c:line=442:obj=unknown:subj=dsigCtx->signValueNode == NULL:error=100:assertion: 
func=xmlSecDSigCtxVerify:file=xmldsig.c:line=352:obj=unknown:subj=xmlSecDSigCtxProcessSignatureNode:error=1:xmlsec library function failed: 
Signal: SIGPIPE (signal SIGPIPE)
```

Did the first check with the "old" certificate somehow broke something it has not recovered from?

**Comment by njaremko** [comment]
Can you try reverting [this change](https://github.com/njaremko/samael/pull/38/files) locally and let me know if it works?

That `SIGPIPE` is strange to see in this context

**Comment by pythoneer** [comment]
Sorry for taking so long! After looking at the mentioned PR i noticed that the error message and problem description is almost the same. Wondering if "reverting this change" can be done by just using an older version of the samael library i noticed that my test code still uses `0.0.13` so i it's the same as the author of the PR. Changing it to the newest `0.0.14` however fixes the problem, like it did in the PR. It appears that the test code was written shortly before that date, "laying around" untouched while google changed the Certs and i did not noticed the new version.

So i am closing this as "duplicate" of https://github.com/njaremko/samael/pull/38 which fixed the problem.
