### ISSUE TITLE
Code Samples for generating SAML requests & reading responses? 

### ISSUE THREAD

**Issue by ashwinsekaran** [njaremko/samael#6]
Could you please help us in providing code samples (Examples) for few important scenario's as how its provided for metadata in readme!

**Comment by njaremko** [comment]
Not sure what you're asking for? Do you have a particular example in mind?

**Comment by ashwinsekaran** [comment]
Like Generating SAML request and reading response for any basic scenario would help us to traverse better! Thanks in Advance

**Comment by njaremko** [comment]
Doing some general cleanup, will try to add better docs soon 👍
