### ISSUE TITLE
About DigestValue and Signature Values

### ISSUE THREAD

**Issue by QiangHeisenberg** [njaremko/samael#9]
It does not appear that the corresponding DigestValue and SignatureValue generation sections are not seen here. I've been puzzled about how these two values are generated.

**Comment by QiangHeisenberg** [comment]
Are we going to add some examples of signatures and signature verification?

**Comment by njaremko** [comment]
If you still have questions, please open a new ticket, closing because this is quite old, and I don't understand the question
